# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable: pkgs-25_05:
{
  inherit (pkgs)
    bitcoin
    bitcoind
    btcpayserver
    electrs
    extra-container
    lndconnect;

  inherit (pkgsUnstable)
    lnd;

  inherit pkgs pkgsUnstable pkgs-25_05;
}
