# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    bitcoin
    bitcoind
    btcpayserver
    electrs
    extra-container
    lndconnect;

  inherit (pkgsUnstable)
    lnd;

  inherit pkgs pkgsUnstable;
}
